name: cypher_system_srd_lookup
description: An instant full-text search app for the Cypher System SRD with structured results.
publish_to: 'none'
version: 1.1.0+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  accordion: ^2.6.0
  collection: ^1.17.2
  flutter:
    sdk: flutter
  go_router: ^10.2.0
  json_annotation: ^4.8.1 
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  path: ^1.8.3
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
  - assets/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: "AppIcon"
  remove_alpha_ios: true
  image_path: "./icons/icon.png"