name: cypher_system_srd_lookup
description: An instant full-text search app for the Cypher System SRD with structured results.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  collection: ^1.17.2
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1 

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  path: ^1.8.3

flutter:
  assets:
  - assets/
  uses-material-design: true
