name: cypher_system_srd_lookup
description: An instant full-text search app for the Cypher System SRD with structured results.
publish_to: 'none'
version: 1.2.1+6

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  accordion: ^2.6.0
  azlistview: ^2.0.0
  collection: ^1.17.2
  flutter:
    sdk: flutter
  go_router: ^10.2.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1 
  path_provider: ^2.1.1
  provider: ^6.0.5
  url_launcher: ^6.1.14

dev_dependencies:
  auto_screenshot: ^0.0.2
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  path: ^1.8.3
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1

flutter:
  assets:
  - assets/
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: "AppIcon"
  remove_alpha_ios: true
  image_path: "./icons/icon.png"

auto_screenshot:
  bundle_id: 
    android: com.isaaclyman.cyphersrd
    ios: com.isaaclyman.cyphersrd
  devices:
    - iPhone 8 Plus
    - iPhone 13 Pro Max
    - iPad Pro (12.9-inch) (2nd generation)
    - iPad Pro (12.9-inch) (5th generation)
    - Pixel_3a_API_33_arm64-v8a
    - Pixel_5_API_33
  base_url:
    android: http://flutterbooksample.com
    ios: customschema://flutterbooksample.com
  screenshot:
    - search
    - search?query=warrior
    - search?categoryName=type&itemName=warrior
    - search?categoryName=ability&itemName=bash
    - browse
