name: bookoscope
description: OPDS crawl & search + free ebooks
publish_to: "none"
version: 1.2.3+6

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  accordion: ^2.6.0
  auto_size_text: ^3.0.0
  collection: ^1.18.0
  csv: ^5.1.1
  flutter:
    sdk: flutter
  go_router: ^12.1.3
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  mockito: ^5.4.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  url_launcher: ^6.2.2
  xml: ^6.5.0

dev_dependencies:
  auto_screenshot:
    path: ../auto_screenshot
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  path: 1.9.0
  flutter_launcher_icons: ^0.13.1
  isar_generator: ^3.1.0+1

flutter:
  assets:
    - assets/
  fonts:
    - family: Titillium
      fonts:
        - asset: fonts/TitilliumWeb-Regular.ttf
        - asset: fonts/TitilliumWeb-Italic.ttf
          style: italic
        - asset: fonts/TitilliumWeb-Bold.ttf
          weight: 500
        - asset: fonts/TitilliumWeb-BoldItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/TitilliumWeb-Light.ttf
          weight: 300
        - asset: fonts/TitilliumWeb-LightItalic.ttf
          style: italic
          weight: 300
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: "AppIcon"
  remove_alpha_ios: true
  image_path: "./icons/icon.png"

auto_screenshot:
  bundle_id:
    android: com.isaaclyman.bookoscope
    ios: com.isaaclyman.bookoscope
  devices:
    - iPhone 8 Plus
    - iPhone 13 Pro Max
    - iPad Pro (12.9-inch) (2nd generation)
    - iPad Pro (12.9-inch) (5th generation)
    - 10-inch_Tablet_API_33
    - 7-inch_Tablet_API_33
  base_url:
    android: http://bookoscope.isaaclyman.com/
    ios: bookoscope://bookoscope.isaaclyman.com
  output_folder: screenshots
  screenshot:
    - search
